-- Create per-user message bookmarks for thread summary cards.
create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  thread_id uuid not null references public.threads(id) on delete cascade,
  message_index integer not null check (message_index >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists bookmarks_user_thread_message_idx
  on public.bookmarks (user_id, thread_id, message_index);

create index if not exists bookmarks_thread_idx
  on public.bookmarks (thread_id, message_index);

alter table public.bookmarks enable row level security;

drop policy if exists bookmarks_select_own on public.bookmarks;
create policy bookmarks_select_own on public.bookmarks
  for select
  using (auth.uid() = user_id);

drop policy if exists bookmarks_insert_own on public.bookmarks;
create policy bookmarks_insert_own on public.bookmarks
  for insert
  with check (auth.uid() = user_id);

drop policy if exists bookmarks_delete_own on public.bookmarks;
create policy bookmarks_delete_own on public.bookmarks
  for delete
  using (auth.uid() = user_id);
